version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: enernova-postgres
    restart: always
    environment:
      POSTGRES_USER: enernova
      POSTGRES_PASSWORD: EnergiTerbarukan22
      POSTGRES_DB: enernova
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
